version: '3.7'
services:
  jaeger:
    image: jaegertracing/all-in-one:latest
    ports:
      - "5775:5775/udp"
      - "16686:16686"
    networks:
      - jaeger-example
  endereco:
    image: tiago89/jaeger-example
    ports:
      - "8081:8080"
    command: ["all"]
    environment:
      - JAEGER_AGENT_HOST=jaeger
      - JAEGER_AGENT_PORT=5775
    networks:
      - jaeger-example
    depends_on:
      - jaeger

networks:
  jaeger-example: